#!/bin/sh
#[.husky / prepare-commit-msg]
#. "$(dirname "$0")/_/husky.sh"

#exec < /dev/tty && npx cz --hook || true

#exec < /dev/tty && git cz --hook || true
#exec < /dev/tty && npx cz --hook || false
#exec < /dev/tty && node_modules/.bin/cz --hook || true
